//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string ugender { get; set; }
        public string uemail { get; set; }
        public string upass { get; set; }
        public Nullable<System.DateTime> udob { get; set; }
        public string uhby { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> cid { get; set; }
        public string uphoto { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> regDate { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
